const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    cardBackground: '#fff',
    inputBorder: '#ddd',
    chartBackground: '#fff',
    legendText: '#7F7F7F',
    pieChartBackground: '#f8f9fa',
    stressLevelBorder: '#007AFF',
    stressLevelBackground: '#f8f9fa',
    deleteButton: '#ff3b30',
    tabBarBorder: '#e0e0e0',
    inputCardShadow: '#000',
    chartCardBackground: '#fff',
    recentEntriesBackground: '#fff',
    entryCardBackground: '#f8f9fa',
    entryDateText: '#666',
    entryText: '#333',
    stressedText: '#ff6b6b',
    notStressedText: '#4cd964',
    emptyStateText: '#666',
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    cardBackground: '#1a1a1a',
    inputBorder: '#333',
    chartBackground: '#1a1a1a',
    legendText: '#aaaaaa',
    pieChartBackground: '#2a2a2a',
    stressLevelBorder: '#007AFF',
    stressLevelBackground: '#2a2a2a',
    deleteButton: '#ff3b30',
    tabBarBorder: '#333',
    inputCardShadow: '#000',
    chartCardBackground: '#1a1a1a',
    recentEntriesBackground: '#1a1a1a',
    entryCardBackground: '#2a2a2a',
    entryDateText: '#aaaaaa',
    entryText: '#ffffff',
    stressedText: '#ff6b6b',
    notStressedText: '#4cd964',
    emptyStateText: '#aaaaaa',
  },
};
